"""
agents/github_agent.py — GitHub Push Agent
===========================================
Responsible for:
  - Forking the target repo under the configured GitHub account
  - Creating a new branch: ai-generated-tests/<timestamp>
  - Committing all generated test files in a single commit
  - Opening a Pull Request with a structured summary

This is the FIFTH agent in the pipeline.
Input  : TestGapReport + path to generated test files
Output : Pull Request URL
"""

import sys
import time
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from github import Github, Auth, InputGitTreeElement, GithubException
from rich.console import Console
from rich.panel import Panel

from config import GITHUB_TOKEN, GITHUB_USERNAME, OUTPUT_DIR
from models.report import TestGapReport

console = Console()

UPSTREAM_REPO  = "fastapi/full-stack-fastapi-template"
DEFAULT_BRANCH = "master"


# ─────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────

def _get_file_destination(filename: str) -> str:
    """
    Map a generated filename → its destination path inside the repo.
      *.spec.ts  → frontend/tests/<name>.spec.ts
      *.py       → backend/tests/<name>.py
    Strips parentheses from names like 'error-(error).spec.ts'.
    """
    safe = filename.replace("(", "").replace(")", "")
    if filename.endswith(".py"):
        return f"backend/tests/{safe}"
    return f"frontend/tests/{safe}"


def _build_pr_body(report: TestGapReport, files: dict[str, str]) -> str:
    high  = [g for g in report.test_gaps if g.priority == "high"]
    med   = [g for g in report.test_gaps if g.priority == "medium"]
    low   = [g for g in report.test_gaps if g.priority == "low"]

    file_list = "\n".join(f"- `{p}`" for p in sorted(files))

    return f"""## 🤖 AI-Generated Playwright Tests

Generated by **[RAG Test Generator](https://github.com/{GITHUB_USERNAME}/rag-test-generator)**
Source repo : `{report.repo_url}`
Generated at: `{report.generated_at}`

---

## Coverage Summary

| Category | Found | Tested (before) | Untested |
|---|---|---|---|
| API Endpoints | {len(report.api_endpoints)} | {sum(e.has_test for e in report.api_endpoints)} | {len(report.untested_endpoints)} |
| UI Pages | {len(report.ui_pages)} | {sum(p.has_test for p in report.ui_pages)} | {len(report.untested_pages)} |
| Test Gaps | {len(report.test_gaps)} | — | {len(report.test_gaps)} |

---

## Authentication Flows Covered

{chr(10).join(f"- {f}" for f in report.auth_flows)}

---

## Test Gaps Addressed

### 🔴 High Priority ({len(high)})
{chr(10).join(f"- **{g.name}** — {g.reason}" for g in high)}

### 🟡 Medium Priority ({len(med)})
{chr(10).join(f"- **{g.name}** — {g.reason}" for g in med)}

### 🟢 Low Priority ({len(low)})
{chr(10).join(f"- **{g.name}** — {g.reason}" for g in low)}

---

## Generated Files

{file_list}

---

## How to Run

```bash
# Playwright tests
cd frontend && npx playwright test tests/

# Python tests
cd backend && pytest tests/ -v
```

---
🤖 *Generated with [RAG Test Generator](https://github.com/{GITHUB_USERNAME}/rag-test-generator) — AI-powered test generation using OpenAI + ChromaDB*
"""


def _wait_for_fork(user, fork_full_name: str, max_wait: int = 30) -> None:
    """GitHub forks are created asynchronously — poll until the repo is ready."""
    for _ in range(max_wait):
        try:
            user.get_repo(fork_full_name.split("/")[1])
            return
        except GithubException:
            time.sleep(1)


# ─────────────────────────────────────────────────────────
# Main entry point
# ─────────────────────────────────────────────────────────

def run(
    report        : TestGapReport,
    generated_dir : Path = OUTPUT_DIR,
) -> str:
    """
    Main entry point for the GitHub push agent.

    Pipeline:
        1. Fork the upstream repo (idempotent — safe to call if fork exists)
        2. Create a new branch off master
        3. Upload all generated test files in a single commit (git tree API)
        4. Open a Pull Request in the fork with a structured summary

    Args:
        report        : TestGapReport from analysis_agent.run()
        generated_dir : Directory containing generated .spec.ts / .py files

    Returns:
        Pull Request URL (string)
    """
    console.print("\n" + "=" * 60)
    console.print("[bold cyan]GITHUB PUSH AGENT[/bold cyan]")
    console.print("=" * 60)

    g        = Github(auth=Auth.Token(GITHUB_TOKEN))
    user     = g.get_user()
    upstream = g.get_repo(UPSTREAM_REPO)

    # ── Step 1: Fork ──────────────────────────────────────
    console.print(f"\n[cyan]🍴 Forking {UPSTREAM_REPO}...[/cyan]")
    try:
        fork = user.create_fork(upstream)
        _wait_for_fork(user, fork.full_name)
        console.print(f"   [green]✅ Fork ready: {fork.html_url}[/green]")
    except GithubException as exc:
        # Already forked — get the existing fork
        if exc.status == 422:
            fork = g.get_repo(f"{GITHUB_USERNAME}/{upstream.name}")
            console.print(f"   [yellow]⚡ Fork already exists: {fork.html_url}[/yellow]")
        else:
            raise

    # ── Step 2: Create branch ─────────────────────────────
    branch_name = f"ai-generated-tests/{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    console.print(f"\n[cyan]🌿 Creating branch: {branch_name}...[/cyan]")

    base_sha = fork.get_branch(DEFAULT_BRANCH).commit.sha
    fork.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
    console.print(f"   [green]✅ Branch created[/green]")

    # ── Step 3: Collect generated test files ──────────────
    files: dict[str, str] = {}
    for path in sorted(generated_dir.glob("*")):
        if path.suffix in (".ts", ".py"):
            dest = _get_file_destination(path.name)
            files[dest] = path.read_text(encoding="utf-8")

    if not files:
        console.print("[red]❌ No generated test files found in {generated_dir}[/red]")
        raise FileNotFoundError(f"No .ts or .py files in {generated_dir}")

    console.print(f"\n[cyan]📁 Staging {len(files)} test files...[/cyan]")
    for dest in sorted(files):
        console.print(f"   [dim]{dest}[/dim]")

    # ── Step 4: Single commit via Git Tree API ─────────────
    console.print(f"\n[cyan]💾 Creating commit...[/cyan]")

    base_tree = fork.get_git_tree(sha=base_sha)

    blobs = []
    for dest_path, content in files.items():
        blob = fork.create_git_blob(content, "utf-8")
        blobs.append(InputGitTreeElement(
            path = dest_path,
            mode = "100644",
            type = "blob",
            sha  = blob.sha,
        ))

    new_tree      = fork.create_git_tree(blobs, base_tree)
    parent_commit = fork.get_git_commit(base_sha)

    commit_msg = (
        f"Add AI-generated tests for {len(files)} untested flows\n\n"
        f"Generated by RAG Test Generator using OpenAI + ChromaDB.\n"
        f"Covers: {len(report.untested_endpoints)} untested API endpoints, "
        f"{len(report.untested_pages)} untested UI pages, "
        f"and {sum(1 for g in report.test_gaps if g.gap_type == 'function')} utility functions."
    )

    commit = fork.create_git_commit(
        message = commit_msg,
        tree    = new_tree,
        parents = [parent_commit],
    )

    branch_ref = fork.get_git_ref(f"heads/{branch_name}")
    branch_ref.edit(sha=commit.sha)
    console.print(f"   [green]✅ Committed {len(files)} files (SHA: {commit.sha[:7]})[/green]")

    # ── Step 5: Open Pull Request ──────────────────────────
    console.print(f"\n[cyan]🔀 Opening Pull Request...[/cyan]")

    pr = fork.create_pull(
        title = "🤖 AI-generated tests for untested flows",
        body  = _build_pr_body(report, files),
        head  = branch_name,
        base  = DEFAULT_BRANCH,
    )

    console.print(Panel(
        f"[bold]Pull Request created![/bold]\n\n"
        f"  Repo   : {fork.full_name}\n"
        f"  Branch : {branch_name}\n"
        f"  Files  : {len(files)} test files committed\n"
        f"  PR     : {pr.html_url}",
        title="[bold green]✅ GitHub Push Complete[/bold green]",
        border_style="green",
    ))

    return pr.html_url


# ─────────────────────────────────────────────────────────
# Quick test — run directly
# python agents/github_agent.py
# ─────────────────────────────────────────────────────────
if __name__ == "__main__":
    import json
    from models.report import TestGapReport, APIEndpoint, UIPage, TestGap

    report_path = Path(__file__).parent.parent / "outputs" / "test_gap_report.json"
    raw = json.loads(report_path.read_text())

    report = TestGapReport(
        repo_url      = raw["repo_url"],
        generated_at  = raw["generated_at"],
        api_endpoints = [APIEndpoint(**e) for e in raw["api_endpoints"]],
        ui_pages      = [UIPage(**p)      for p in raw["ui_pages"]],
        auth_flows    = raw["auth_flows"],
        test_gaps     = [TestGap(**g)     for g in raw["test_gaps"]],
    )

    pr_url = run(report)
    console.print(f"\n[bold green]PR URL: {pr_url}[/bold green]")
